### ISSUE TITLE
Erebus Wings?

### ISSUE THREAD

**Issue by Shahelion** [Tombenpotter/Icarus#17]
Possible materials:
- [x] Jade (the "diamond" of the erebus)
- [x] Exoskeleton Plates, Reinforced Exoskeleton Plates, Rhino Plates & Horns
- [x] Altar Fragments (very rarely from fossil ore)
- [x] Petrified Wood (mid-rarity ore)

Perhaps have a lower max height, but better gliding.

Jade-Adorned Exoskeleton Wings? Petrified Golem Wings?

**Comment by Tombenpotter** [comment]
I'm not familiar at all with Erebus. If you could give me a progression line, I will probably do it! :)

**Comment by Shahelion** [comment]
It's not really a progression-based mod. It adds the Erebus dimension, the world of bugs. There are a few dungeon types, and two bosses/minibosses, but it's mostly exploration-based.

Jade is a rare ore, comparable to diamonds apparently in terms of generation (although all vanilla ores still do generate in the Erebus). 
Petrified Wood Ore is roughly as common as iron, dropping one piece per ore, used to make special chests and such. 
Altar Fragments are rarely dropped from fossil ore, which normally drops bone fragments (used for bonemeal and arrows). They are used to make various altars such as healing and lightning, and to craft the Umbergolem.
Exoskeleton Plates are dropped by a few types of beetles, and are used to make armor and a few other things. 9 Plates makes a Reinforced Plate, those make even better armor. Rhino Beetles drop Rhino Plates and Horns, which makes armor that is nearly identical to Diamond Armor except it looks much better.

Just thought of another thing, perhaps have Fly Wings replace the feathers in the wing recipes. They already serve as feather alternatives for arrows, like Bone Shards are alternate flint.

It's a pretty tough dimension to live in, but it is possible to survive in it, although ranged weaponry is almost mandatory.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2244153-latest-erebus-update-0-3a-released
