### ISSUE TITLE
Wings from Immersive Engineering's hemp fabric

### ISSUE THREAD

**Issue by nmarshall23** [Tombenpotter/Icarus#18]
I check [Immersive Engineering | https://github.com/BluSunrize/ImmersiveEngineering] github, they have an api should be straight forward to add a wings made from hemp fabric. 

I'm not sure what stats hemp fabric wings should have. Possibly good gliding factor.

**Comment by Tombenpotter** [comment]
Will do :D

**Comment by Tombenpotter** [comment]
Done. Added Treated Cardboard wings too!
