### ISSUE TITLE
"Complete Set" Wing Type suggestions

### ISSUE THREAD

**Issue by Shahelion** [Tombenpotter/Icarus#19]
These are mostly wings that would function to complete an armor set, where the set provides a bonus. I have no idea how many of these, if any, are even possible.
- [ ] [Twilight Forest] Fiery Wings: Fiery Ingots. Particle after-trail if possible, Fiery Aura effect (same as the Fiery armor set, to still allow for the set effect when wearing the wings).
- [ ] [Blood Magic] Wings of the Nine Hells: similar to Bound Armor, uses LP to repair, and to lower damage taken.
- [x] [Witchery] Witch Hunter's Mantle: Nullified Leather and Null Catalyst. Activates set bonus of Witch Hunter Armor (protection from curses).
- [x] [Witchery] Black Manteau: Woven Cruor. Contributes to set bonus of the Vampire Clothes, Fire Resistance (different from the vanilla effect).
- [x] [Botania] Mana Gliders: Manasteel or Manaweave Cloth. Uses Mana to repair. If Manaweave Cloth, Mana Discount with Rods.
- [ ] [Thaumic Tinkerer] Wings of Ichor: Ichorcloth and Ichorium Ingots. Simply unbreakable, maybe not the highest maximum height of all wing types to counterbalance this.

---

Various materials required: https://gyazo.com/2ff73c0f3f27047a887e2bf4602804b4
Left to right: Blood Magic, Manasteel Ingot, Manaweave Robes (both halves), Ichorcloth, Fiery Ingot, Exoskeleton Plate and Reinforced Plate (for the Erebus wings), Null Catalyst, Nullified Leather, Woven Cruor.

This is just for the colors and styles and such.

**Comment by Tombenpotter** [comment]
Bound wings are waiting for something to be fixed in the BM API, but I'll definitely do something for the others. 

Well, it looks like you have some work @GustoniaEagle :D

**Comment by Shahelion** [comment]
I just remembered that Witchery doesn't have an API (yet). I don't know if that would affect this, but apparently it prevents Witchery add-ons from being made so it might.

**Comment by Tombenpotter** [comment]
The worst that could happen when making the armor would be me needing to ask Emoniph a couple of questions. 

Regular armor isn't hard. What will be the issue is doing the fire protection and the protection to curses.

**Comment by Tombenpotter** [comment]
Boop

**Comment by Tombenpotter** [comment]
Added some of these wings, others will come later!

**Comment by Shahelion** [comment]
Feel free to re-open this if needed, but I feel like this isn't being worked on anymore.
