### ISSUE TITLE
Rain and Enderium Wings cause a crash

### ISSUE THREAD

**Issue by novasolarius** [Tombenpotter/Icarus#20]
IT BROKE! http://pastebin.com/cti4caN5
Nothing special to tell you. I made Enderium wings with Project E, flew around for a bit, then crashed when it started to rain. Had to remove Icarus to regain access to the world.

**Comment by Tombenpotter** [comment]
Siigh. I was hoping this wouldn't happen. I'll release a fix soon <.<

**Comment by novasolarius** [comment]
Thanks.

**Comment by Tombenpotter** [comment]
Bug is fixed, new version out on curse.
