### ISSUE TITLE
Terrasteel Wings can't be crafted, 2x Terrasteel Wing returns Manasteel Wings

### ISSUE THREAD

**Issue by novasolarius** [Tombenpotter/Icarus#21]
Title says it all, combining two Terrasteel Wing items returns Manasteel Wings, not Terrasteel. All the other recipes work fine, it's only Terrasteel.

**Comment by Tombenpotter** [comment]
Craaap. Copy paste is bad!
https://github.com/Tombenpotter/Icarus/blob/master/src/main/java/tombenpotter/icarus/common/IcarusItems.java#L107
I'm sorry, I'll fix that tomorrow first thing!

**Comment by novasolarius** [comment]
That's okay. Keep up the great work!

**Comment by Tombenpotter** [comment]
Fixed in the pull request above
