### ISSUE TITLE
No fall damage

### ISSUE THREAD

**Issue by Tombenpotter** [Tombenpotter/Icarus#25]
You're supposed to take fall damage when you let yourself slowly descend. You need to flap your wings at least once to prevent this.
I know how to fix this, I just didn't get to it yet.

**Comment by Shahelion** [comment]
Well it makes sense if you're shifting to fall faster, but slowly gliding down should at least reduce fall damage.

**Comment by Tombenpotter** [comment]
Fall damage is reduced by a factor that depends on the wings. It was there before, but as it was bugged, nobody ever saw the difference :P

**Comment by Tombenpotter** [comment]
Closed by d8628624c85f9e816b9f8925deff6ce52c2e73d8
