### ISSUE TITLE
Errored Recipe

### ISSUE THREAD

**Issue by Shahelion** [Tombenpotter/Icarus#26]
Hardcore Ender Expansion caught an erroring recipe while the pack was loading. It tries to disable recipes that would possibly crash.

[22:56:49] [Client thread/ERROR] [HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: [TIcarus]item.Icarus.singleWing/6 <= {[Railcraft]item.railcraft.ingot/3(ore), [Railcraft]item.railcraft.ingot/3(ore), <empty>, [Railcraft]item.railcraft.ingot/3(ore), error:null, error:null, <empty>, [Railcraft]item.railcraft.ingot/3(ore), [Railcraft]item.railcraft.ingot/3(ore)}

**Comment by Shahelion** [comment]
I should also mention that I have no idea what wings this recipe is for. 

There are also no ore dictionary wings besides the Bronze ones in my instance.

**Comment by Tombenpotter** [comment]
Having a quick look through the code, the issue comes from Leadstone wings. If you don't have Thermal Expansion in your mods, try to disable the compatibility for it in the config. I'll try to fix this once I'm home a bit later today

**Comment by Shahelion** [comment]
If I don't have TE, but spawn the wings in or make an alternate recipe for them, will they still work? I have other RF-using mods such as Immersive Engineering  and EnderIO. This would be just to have RF-powered wings until other mod variants are added.

Also what does the Ore Dictionary Wings bit refer to? I don't see any in NEI that would fit that category except maybe Bronze.

**Comment by Tombenpotter** [comment]
At the moment it's mainly bronze, but there will be others like steel, peridot, ruby, sapphire, etc. 
And yes, it's just the recipe that's broken, the wings will still work. And EnderIO wings are coming next version anyways ;)

**Comment by Tombenpotter** [comment]
d8628624c85f9e816b9f8925deff6ce52c2e73d8 should fix this issue
