### ISSUE TITLE
Cross-Mod Suggestion: Traveller's Gear/Witching Gadgets (TC add-on)

### ISSUE THREAD

**Issue by Shahelion** [Tombenpotter/Icarus#27]
Traveller's Gear adds a Cloak slot, perhaps have an option to use that for wings, and have it so they don't provide additional armour if in that slot, purely utility. Not sure if that's possible, though.

Also Bewitched Thread, and Cloth of Spacious Folds. Eldritch Wings?

**Comment by Tombenpotter** [comment]
I've thought about it in more depth. I won't do it, for the exact same reason I don't want to do it with Baubles. The wings stay in the chestplate slot. Sorry :/
