### ISSUE TITLE
Oredictionary conflict

### ISSUE THREAD

**Issue by RedsaphirCZ** [Tombenpotter/Icarus#35]
Hello.
If i add your mod to one modpack with Project red, you are now able to make ruby wings (and anything else what use ruby sapphire peridot) out of cooked porkchop, sapphire out of steak and peridot out of cooked chicken. I tested it :) this is probably some oredictionary problem. thanks for help :)

**Comment by Tombenpotter** [comment]
CRAP.
That's what happen when you don't check if testing code works -_-

**Comment by Tombenpotter** [comment]
Hotfix released on curse, pending approval

EDIT: Approved.

**Comment by RedsaphirCZ** [comment]
Thanks for the hotfix, keep up great work :+1:
