### ISSUE TITLE
Issue with Void Metal Wings & Aura Cascade request

### ISSUE THREAD

**Issue by SkullyGamingMC** [Tombenpotter/Icarus#4]
Hey Tombenpotter! I was wondering if you could add Aura Cascade integration with Icarus. When I say integration, I mean Angel's Steel Wings. Along with that, I also found that you may have swapped the IDs for the Enderium Wing and the Void Metal Wing, as the Void Metal recipe makes an Enderium Wing, which two are used to make Void Metal Wings.

**Comment by Tombenpotter** [comment]
Aura Cascade compatibility sounds good to me! I'll do that once I can code again... And I think I'll make sure to never again have issues with the Ids -_-
Way to feel stupid!

**Comment by Tombenpotter** [comment]
Issue fixed by #5. Will add the wings later
