### ISSUE TITLE
Manasteel Wings become useless when paired with armor

### ISSUE THREAD

**Issue by Shahelion** [Tombenpotter/Icarus#71]
Wings: Manasteel
Armor: Thaumaturge Robes

The crafting recipe in NEI shows shapeless, but it only worked if the armor was one down and to the right of the wings(in the 2x2 grid, in the 3x3 grid it's fine).

The wings turned purple and have the tooltip "Armor Rendered: Thaumaturge's Robe"

However, the wings are now useless. They can't be flapped, and don't lose durability.

**Comment by Shahelion** [comment]
After further experimentation, this only seems to apply to the Manasteel Wings.
Tested:
Manaweave Wings & Manasteel Armor: works
Manasteel Wings & Manasteel Armor: doesn't work
Thaumium Wings & Thaumaturge's Robes: works

Also, can Botania wings be repaired by Mana, and can Thaumcraft wings accept the Repair enchantment?

**Comment by Tombenpotter** [comment]
Manasteel wings need Mana to fly. Are you sure you have enough of it left?

**Comment by Shahelion** [comment]
Did not realize they needed mana. Shouldn't Manaweave wings also need it?
